name: C/C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Compile
      run: |
        cd hmm_sim
        make
      
    - name: Test
      run: |
        cd hmm_sim
        chmod +x ./tests/testScript.sh
        make testHmm
        
    - name: Stress Test
      run: |
        cd hmm_sim
        make testStress 